trigger:
 - bicep
pool:
  vmImage: 'ubuntu-20.04'
steps:
- task: AzureCLI@2
  displayName: 'Azure CLI '
  inputs:
    azureSubscription: AzureFucn
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: 'az deployment group create -g newdev -f main.bicep'
