trigger:
 - bicepinfra
pool:
 vmImage: windows-latest

stages:
    - stage: creating_variables_on_job
      jobs:
       - job: 
         steps:
           - task: Bash@3
             inputs:
               targetType: 'inline'
               script: |
                Current_IP=$(curl ipinfo.io/ip)
                echo $Current_IP

      
  



