trigger:
 - bicepinfra
pool:
 name: Azure Pipelines

stages:
    - stage: creating_variables_on_job
      jobs:
          - job: creating_variables
            displayName: Determine paths changed to understand jobs to run
            steps:
            - task: Bash@3
              name: 'ADO_variables'
              displayName: 'creating_variables'    
              inputs:
                targetType: 'inline'
                script: |
                  #!/bin/sh
                  echo "##vso[task.setvariable variable=Orders_Changed;isOutput=true]true"
                  echo "##vso[task.setvariable variable=User_Changed;isOutput=true]true" 
            - task: Bash@3
              name: 'checking_code_changes_script'
              displayName: 'checking_code_changes_script'
              inputs:
               filePath: 'script.sh'
             
          - job: Order_changes
            displayName: 'Checking Order files changing'
            dependsOn: creating_variables
            condition: eq(dependencies.creating_variables.outputs['ADO_variables.Orders_Changed'], 'true') 
            steps:
              - task: DotNetCoreCLI@2
                inputs:
                  projects: 'src/Kerry.SSP.Orders.API/*.csproj'
                  arguments: '--output publish_output --configuration Release'
              - task: ArchiveFiles@2
                displayName: 'Archive files'
                inputs:
                  rootFolderOrFile: 'publish_output/'
                  includeRootFolder: false

              - task: PublishBuildArtifacts@1
                displayName: 'Publish Artifact: drop' 


          - job: User_changes
            displayName: 'checking user files'
            dependsOn: creating_variables
            condition: eq(dependencies.creating_variables.outputs['ADO_variables.User_Changed'], 'true')
            steps:
              - task: DotNetCoreCLI@2
                inputs:
                  projects: 'src/Kerry.SSP.User.API/*.csproj'
                  arguments: '--output publish_output --configuration Release'

              - task: ArchiveFiles@2
                displayName: 'Archive files'
                inputs:
                  rootFolderOrFile: 'publish_output/'
                  includeRootFolder: false    
              - task: PublishBuildArtifacts@1
                displayName: 'Publish Artifact: drop' 

  



