trigger:
  - None
pool:
  vmImage: 'windows-latest'  
stages:
  - stage: build_project_archive_publish
    jobs:
      - job: 
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'Build project'
            inputs:
              projects: '**/*.csproj'
              arguments: '--output publish_output --configuration Release'
          - task: ArchiveFiles@2
            displayName: 'Archive files'
            inputs:
              rootFolderOrFile: 'publish_output/'
              includeRootFolder: false
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: drop'   
  - stage: Stage
    displayName: stage
    dependsOn: build_project_archive_publish
    condition: succeeded('build_project_archive_publish')
    jobs:
    - deployment: APIDeployment 
      displayName: 'API Deployment'
      environment: 'development'
    pool: 
      vmImage: 'windows-latest'
    strategy:
      runOnce:
      deploy:
       steps:
       -task:
        