trigger:
  - newazurefun
pool:
  vmImage: 'windows-latest'  
stages:
  - stage: build_project_archive_publish
    jobs:
      - job: 
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'Build project'
            inputs:
              projects: '**/*.csproj'
              arguments: '--output publish_output --configuration Release'
          - task: ArchiveFiles@2
            displayName: 'Archive files'
            inputs:
              rootFolderOrFile: 'publish_output/'
              includeRootFolder: false
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: drop'   
