trigger:
  - newazurefun
pool:
  name: Azure Pipelines  
stages:
  - stage: build_project
    jobs:
      - job: 
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'Build project'
            inputs:
              projects: '**/*.csproj'
              arguments: '--output publish_output --configuration Release'
          - task: ArchiveFiles@2
            displayName: 'Archive files'
            inputs:
              rootFolderOrFile: 'publish_output/'
              includeRootFolder: false
  - stage: publish_artifcats
    jobs:
      - job:  
        steps:
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: drop'
